name 'demo-chef-provisioning'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures demo-chef-provisioning'
long_description 'Installs/Configures demo-chef-provisioning'
version '0.1.0'
